name: Build-Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'
          check-latest: true
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build notation-venafi-csp
        run: |
          make cross
          tar --no-xattrs --transform='flags=r;s|notation-venafi-csp-darwin-amd64|notation-venafi-csp|' -cvzf notation-venafi-csp-darwin-amd64.tar.gz notation-venafi-csp-darwin-amd64
          tar --no-xattrs --transform='flags=r;s|notation-venafi-csp-darwin-arm64|notation-venafi-csp|' -cvzf notation-venafi-csp-darwin-arm64.tar.gz notation-venafi-csp-darwin-arm64
          tar --no-xattrs --transform='flags=r;s|notation-venafi-csp-linux-amd64|notation-venafi-csp|' -cvzf notation-venafi-csp-linux-amd64.tar.gz notation-venafi-csp-linux-amd64
          tar --no-xattrs --transform='flags=r;s|notation-venafi-csp-linux-arm64|notation-venafi-csp|' -cvzf notation-venafi-csp-linux-arm64.tar.gz notation-venafi-csp-linux-arm64
          mv notation-venafi-csp-windows-amd64 notation-venafi-csp-windows-amd64.exe
          cp notation-venafi-csp-windows-amd64.exe notation-venafi-csp.exe
          zip notation-venafi-csp-windows-amd64.zip notation-venafi-csp.exe
          shasum -a 256 notation-venafi-csp-darwin-amd64.tar.gz > notation-venafi-csp-darwin-amd64.tar.gz.sha256
          shasum -a 256 notation-venafi-csp-darwin-arm64.tar.gz > notation-venafi-csp-darwin-arm64.tar.gz.sha256
          shasum -a 256 notation-venafi-csp-linux-amd64.tar.gz > notation-venafi-csp-linux-amd64.tar.gz.sha256
          shasum -a 256 notation-venafi-csp-linux-arm64.tar.gz > notation-venafi-csp-linux-arm64.tar.gz.sha256
          shasum -a 256 notation-venafi-csp-windows-amd64.zip > notation-venafi-csp-windows-amd64.zip.sha256
          rm *.exe
      - name: Upload artifacts
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            notation-*
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "notation-*"
          bodyFile: "CHANGELOG.md"
           