name: Plugin installer tests
# Run on every push, and allow it to be run manually.
on:
  workflow_dispatch:
  push:
    branches: ['main', 'v*']
  pull_request:

env:
  NOTATION_VERSION: 1.1.0
  PLUGIN_VERSION: 0.3.0
  PLUGIN_LINUX_AMD64_SHA256: "03771794643f18c286b6db3a25a4d0b8e7c401e685b1e95a19f03c9356344f5a"
  PLUGIN_DARWIN_AMD64_SHA256: "2b8293bdfc706a8acbb1fb3b3ce7b37a300d8c2f26e2ecf158db0104fc152348"
  PLUGIN_WINDOWS_AMD64_SHA256: "81fd7e5b200a072c2fd69cf45d6e2de83930e3346debdcfd47c9c45d843d6b3e"

jobs:
  ubuntu-installer-test:
    name: Ubuntu installer test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup notation CLI
        uses: notaryproject/notation-action/setup@v1
        with:
          version: ${{ env.NOTATION_VERSION }}
      - name: Install Venafi plugin
        run: |
          notation plugin install --url https://github.com/Venafi/notation-venafi-csp/releases/download/v${{ env.PLUGIN_VERSION }}/notation-venafi-csp-linux-amd64.tar.gz --sha256sum ${{ env.PLUGIN_LINUX_AMD64_SHA256 }}
          notation plugin ls
  macos-installer-test:
    name: MacOS installer test
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - name: Setup notation CLI
        uses: notaryproject/notation-action/setup@v1
        with:
          version: ${{ env.NOTATION_VERSION }}
      - name: Install Venafi plugin
        run: |
          notation plugin install --url https://github.com/Venafi/notation-venafi-csp/releases/download/v${{ env.PLUGIN_VERSION }}/notation-venafi-csp-darwin-amd64.tar.gz --sha256sum ${{ env.PLUGIN_DARWIN_AMD64_SHA256 }}
          notation plugin ls
  windows-installer-test:
      name: Windows installer test
      runs-on: windows-latest
      permissions:
        contents: read
      steps:
        - name: Setup notation CLI
          uses: notaryproject/notation-action/setup@v1
          with:
            version: ${{ env.NOTATION_VERSION }}
        - name: Install Venafi plugin
          run: |
            notation plugin install --url https://github.com/Venafi/notation-venafi-csp/releases/download/v${{ env.PLUGIN_VERSION }}/notation-venafi-csp-darwin-amd64.tar.gz --sha256sum ${{ env.PLUGIN_WINDOWS_AMD64_SHA256 }}
            notation plugin ls

  windows-old-installer-test:
    name: Windows (OLD) installer test
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: download notation
        shell: pwsh
        run: |
          echo "Downloading notation version"
          curl -sL https://github.com/notaryproject/notation/releases/download/v${{ env.NOTATION_VERSION }}/notation_${{ env.NOTATION_VERSION }}_windows_amd64.zip -o notation.zip
          Expand-Archive -Path notation.zip
      - name: run windows installer
        shell: pwsh
        run: |
          # Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://github.com/venafi/notation-venafi-csp/install/install.ps1')) 
          cd install
          ./install.ps1
      - name: test plugin
        shell: pwsh
        run: |
          cd notation
          ./notation plugin ls
  